#:schema node_modules/wrangler/config-schema.json
name = "workers-ai-image-playground"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[ai]
binding = "AI"

[vars]
CLOUDFLARE_ACCOUNT_ID = "fa2447cb2436447687fda55792256e9e"
